[build.environment]
NPM_FLAGS = "--version"
NODE_VERSION = "18"

[build]
base = "/"
publish = "packages/docs/docs/.vitepress/dist"
command = "pnpm run build:docs"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
