[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  base = "/"
  publish = "packages/docs/docs/.vitepress/dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build:docs"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ./packages/docs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
