[build.environment]
NPM_FLAGS = "--version"
NODE_VERSION = "18"

[build]
base = "/"
publish = "/docs/.vitepress/dist"
command = "pnpm run docs:build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
